<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXxy0gJG\App_KernelTestTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXxy0gJG/App_KernelTestTestDebugContainer.php') {
    touch(__DIR__.'/ContainerXxy0gJG.legacy');

    return;
}

if (!\class_exists(App_KernelTestTestDebugContainer::class, false)) {
    \class_alias(\ContainerXxy0gJG\App_KernelTestTestDebugContainer::class, App_KernelTestTestDebugContainer::class, false);
}

return new \ContainerXxy0gJG\App_KernelTestTestDebugContainer([
    'container.build_hash' => 'Xxy0gJG',
    'container.build_id' => '6aa683c8',
    'container.build_time' => 1741039768,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXxy0gJG');
