<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQdtRDPD\App_KernelTestTestContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQdtRDPD/App_KernelTestTestContainer.php') {
    touch(__DIR__.'/ContainerQdtRDPD.legacy');

    return;
}

if (!\class_exists(App_KernelTestTestContainer::class, false)) {
    \class_alias(\ContainerQdtRDPD\App_KernelTestTestContainer::class, App_KernelTestTestContainer::class, false);
}

return new \ContainerQdtRDPD\App_KernelTestTestContainer([
    'container.build_hash' => 'QdtRDPD',
    'container.build_id' => '4e035ff0',
    'container.build_time' => 1741065577,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQdtRDPD');
