services:
  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx.Dockerfile
    depends_on:
      - php
      - db
    container_name: php_nginx
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./app:/var/www/html
  db:
    image: mysql:8.0.27
    platform: linux/amd64
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ddd_db_1
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - '3306:3306'
    volumes:
      - db_data:/var/lib/mysql

  php:
    build:
      context: .
      dockerfile: ./docker/php.Dockerfile
    volumes:
      - ./app:/var/www/html
    environment:
      XDEBUG_MODE: coverage
      PHP_INI_MEMORY_LIMIT: 1G
    depends_on:
      - db

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - '8181:80'
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    depends_on:
      - db

volumes:
  db_data:
