<?php

namespace ContainerQdtRDPD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrineEntityManagerService extends App_KernelTestTestContainer
{
    /*
     * Gets the private 'App\Infrastructure\Persistence\DoctrineEntityManager' shared autowired service.
     *
     * @return \Doctrine\ORM\EntityManagerInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Infrastructure\\Persistence\\DoctrineEntityManager'] = \App\Infrastructure\Persistence\DoctrineEntityManagerFactory::create();
    }
}
