<?php

namespace ContainerQdtRDPD;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrineUserRepositoryService extends App_KernelTestTestContainer
{
    /*
     * Gets the private 'App\Infrastructure\Repository\DoctrineUserRepository' shared autowired service.
     *
     * @return \App\Infrastructure\Repository\DoctrineUserRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Infrastructure\\Repository\\DoctrineUserRepository'] = new \App\Infrastructure\Repository\DoctrineUserRepository(($container->privates['App\\Infrastructure\\Persistence\\DoctrineEntityManager'] ?? $container->load('getDoctrineEntityManagerService')));
    }
}
