<?php

namespace ContainerXxy0gJG;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrineEntityManagerService extends App_KernelTestTestDebugContainer
{
    /**
     * Gets the private 'App\Infrastructure\Persistence\DoctrineEntityManager' shared autowired service.
     *
     * @return \Doctrine\ORM\EntityManagerInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/persistence/src/Persistence/ObjectManager.php';
        include_once \dirname(__DIR__, 4).'/vendor/doctrine/orm/src/EntityManagerInterface.php';
        include_once \dirname(__DIR__, 4).'/Infrastructure/Persistence/DoctrineEntityManagerFactory.php';

        return $container->privates['App\\Infrastructure\\Persistence\\DoctrineEntityManager'] = \App\Infrastructure\Persistence\DoctrineEntityManagerFactory::create();
    }
}
