<?php

namespace ContainerP6FMt6l;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDoctrineUserRepositoryService extends App_KernelTestTestDebugContainer
{
    /**
     * Gets the private 'Infrastructure\Repository\DoctrineUserRepository' shared autowired service.
     *
     * @return \Infrastructure\Repository\DoctrineUserRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['Infrastructure\\Repository\\DoctrineUserRepository'] = new \Infrastructure\Repository\DoctrineUserRepository();
    }
}
