<?php

namespace ContainerP6FMt6l;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRegisterUserControllerService extends App_KernelTestTestDebugContainer
{
    /**
     * Gets the public 'App\Infrastructure\Presentation\Controller\RegisterUserController' shared autowired service.
     *
     * @return \App\Infrastructure\Presentation\Controller\RegisterUserController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/Infrastructure/Presentation/Controller/RegisterUserController.php';

        return $container->services['App\\Infrastructure\\Presentation\\Controller\\RegisterUserController'] = new \App\Infrastructure\Presentation\Controller\RegisterUserController(($container->privates['App\\Application\\UseCase\\RegisterUser'] ?? $container->load('getRegisterUserService')), ($container->privates['serializer'] ?? self::getSerializerService($container)), ($container->privates['validator'] ?? self::getValidatorService($container)));
    }
}
